[package]
name = "raft"
version = "0.0.1"
authors = ["Andrew Hobden <andrew@hoverbear.org>"]

build = "build.rs"

[build-dependencies]
  capnpc = "*"

[dependencies]
  capnp = "*"
  log = "*"
  rand = "*"
  threadpool = "*"

[dev-dependencies]
  env_logger = "*"
