[package]
name = "raft"
version = "0.0.1"
authors = ["Andrew Hobden <andrew@hoverbear.org>"]

build = "build.rs"

[build-dependencies]
  capnpc = "*"

[dependencies]
log = "*"
rand = "*"

[dependencies.capnp]
git = "https://github.com/dwrensha/capnproto-rust.git"
